[tool.black]
line-length = 100
include = '\.pyi?$'
skip-string-normalization = true
extend-ignore = 'E203'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
